In [4]:
import argparse
import numpy as np
import cv2
import os
image = np.float32(cv2.imread("example/harry.jpg"))
def readPoints(src_path) :
    """
    [Official code]:
    Read points from text file
    """
    face_points = []
    # Read face_points
    with open(src_path) as file :
        for lines in file :
            x, y = lines.split()
            face_points.append((int(x), int(y)))

    return face_points

def addAdditionalPoints(face_points, size) :
    """
    Append 8 additional points: corners and half way points to the face_points list
    """

    height = size[0]
    width = size[1]
    middle_height = height // 2
    middle_width = width // 2
    # Corners
    face_points.append((0, 0))
    face_points.append((0, height - 1))
    face_points.append((width - 1, 0))
    face_points.append((width - 1, height - 1))
    # Half way points
    face_points.append((0, middle_height))
    face_points.append((middle_width, 0))
    face_points.append((width - 1, middle_height))
    face_points.append((middle_width, height - 1))

    return face_points
def build_delaunay(image, points) :
    """
    Gets delaunay 2D segmentation and return a list with the the triangles' indexes
    """
    rectangle = (0, 0, image.shape[1], image.shape[0])
    subdiv = cv2.Subdiv2D(rectangle)
    for point in points :
        subdiv.insert(point)

    triangle_list = subdiv.getTriangleList()
    delaunay_triangles = []
    for p in triangle_list :
        vertexes = [0, 0, 0]

        for v in range(3) :
            vv = v * 2
            for i in range(len(points)) :
                if p[vv] == points[i][0] and p[vv+1] == points[i][1] :
                    vertexes[v] = i

        delaunay_triangles.append(vertexes)

    return delaunay_triangles

In [8]:
points = addAdditionalPoints(readPoints("example/harry.txt"), image.shape)


In [9]:
rectangle = (0, 0, image.shape[1], image.shape[0])
subdiv = cv2.Subdiv2D(rectangle)
for point in points :
    subdiv.insert(point)
triangle_list = subdiv.getTriangleList()

In [21]:
print(triangle_list)

[[ 926.  481.  898.  520.  895.  495.]
 [ 898.  520.  926.  481.  939.  482.]
 [ 640.    0.  896.  472.    0.  480.]
 [ 896.  472.  640.    0.  899.  452.]
 [ 640.    0.    0.  480.    0.    0.]
 [ 994.  542.  970.  535.  972.  516.]
 [ 970.  535.  994.  542.  983.  547.]
 [ 640.  959.  895.  495.  898.  520.]
 [ 895.  495.  640.  959.    0.  480.]
 [ 896.  472.  895.  495.    0.  480.]
 [ 895.  495.  896.  472.  917.  475.]
 [ 949.  570.  961.  548.  961.  567.]
 [ 961.  548.  949.  570.  952.  543.]
 [ 640.  959.  898.  520.  903.  544.]
 [ 971.  551.  971.  571.  961.  567.]
 [ 971.  571.  971.  551.  982.  568.]
 [ 640.  959.  903.  544.  910.  568.]
 [ 903.  544.  898.  520.  952.  543.]
 [ 960.  575.  959.  587.  948.  583.]
 [ 959.  587.  960.  575.  961.  575.]
 [   0.  480.  640.  959.    0.  959.]
 [ 910.  568.  903.  544.  952.  543.]
 [ 982.  587.  982.  575.  983.  575.]
 [ 982.  575.  982.  587.  971.  576.]
 [ 640.  959.  910.  568.  921.  592.]
 [ 921.  592.  910.  568.

In [22]:
triangle_list = triangle_list.astype(np.int32)

In [35]:
print(points[0])
print(triangle_list[0])
vertex = (int(triangle_list[0][0]), int(triangle_list[0][1]))
print(vertex)
v = (-1, -1)
print(vertex in points)

(896, 472)
[926 481 898 520 895 495]
(926, 481)
True
